version: '3.3'
services:
    web:
        container_name: web
        image: php:5.6-apache
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80

    db:
        container_name: db
        image: mariadb:10.6
        environment:
            MYSQL_ROOT_PASSWORD: wjstjf
            MYSQL_DATABASE: hacking
        ports:
            - 3306:3306
